name: Deploy Frontend to EC2

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Create .env.production
        run: |
          echo "${{ secrets.ENV_PRODUCTION }}" > .env.production

      - name: Install dependencies
        run: npm install

      - name: Build frontend
        run: npm run build

      - name: Zip build folder
        run: |
          cd build
          zip -r ../build.zip .

      - name: Add SSH key
        run: |
          echo "$EC2_KEY" > key.pem
          chmod 600 key.pem
        env:
          EC2_KEY: ${{ secrets.EC2_KEY }}
  
      - name: Add EC2 host to known_hosts
        run: |
            ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
  
      - name: Upload build to EC2
        run: |
            scp -i key.pem build.zip ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ec2-user/react-app/


      - name: Deploy on EC2
        run: |
          ssh -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/react-app
            unzip -o build.zip -d build
            sudo rm -rf /usr/share/nginx/html/*
            sudo cp -r build/* /usr/share/nginx/html/
            sudo chmod -R 755 /usr/share/nginx/html
            sudo systemctl restart nginx
          EOF